root = "."
tmp_dir = "tmp"

[build]
  bin = "./scripts/air.sh"
  cmd = "./scripts/tailwind.sh"
  include_dir = ["web/templates"]
  include_ext = ["html"]
  delay = 1000
  exclude_unchanged = false
  follow_symlink = false
  kill_delay = "500ms"
  log = "build-errors.log"
  stop_on_error = true

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  time = false

[misc]
  clean_on_exit = true
