root = "."
tmp_dir = "tmp"

[build]
  bin = "./scripts/air.sh"
  cmd = "./scripts/tailwind.sh && cd web && zola build"
  delay = 1000
  exclude_dir = ["web/public", "web/static", "tmp", "bin"]
  exclude_file = []
  exclude_regex = []
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  include_dir = []
  include_ext = ["md", "html", "css"]
  kill_delay = "500ms"
  log = "build-errors.log"
  stop_on_error = true

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  time = false

[misc]
  clean_on_exit = true
