name: update-and-publish

on:
  schedule:
  # run every 12 hours
  - cron: '0 */12 * * *'

env:
  CARGO_TERM_COLOR: always

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4

    - name: generate
      run: |
        git config --global --add safe.directory '*'
        ./scripts/install-tailwind.sh
        ./scripts/install-pagefind.sh
        ./scripts/bips.sh
        ./scripts/tailwind.sh
        ./scripts/static.sh
        ./scripts/generate.sh

    - name: zola
      run: |
        wget -q https://github.com/getzola/zola/releases/download/v0.18.0/zola-v0.18.0-x86_64-unknown-linux-gnu.tar.gz
        tar xzf zola*.tar.gz
        cd web && ../zola build && cd ..
        rm -rf zola*

    - name: pagefind
      run: |
        pagefind --site web/public

    - name: commit and push
      uses: EndBug/add-and-commit@v7.2.0
      with:
        default_author: github_actions
        branch: master
        message: 'cron: update bips submodule and build'
        push: true
