name: update-and-publish

on:
  schedule:
  # run every 12 hours
  - cron: '0 */12 * * *'

env:
  CARGO_TERM_COLOR: always

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: generate
      run: |
        git config --global --add safe.directory '*'
        ./scripts/install-tailwind.sh
        ./scripts/install-pagefind.sh
        ./scripts/bips.sh
        ./scripts/tailwind.sh
        ./scripts/static.sh
        ./scripts/generate.sh

    - name: build
      uses: shalzz/zola-deploy-action@v0.18.0
      env:
        BUILD_DIR: web
        BUILD_ONLY: true

    - name: pagefind
      run: |
        pagefind --site web/public

    - name: commit and push
      uses: EndBug/add-and-commit@v7.2.0
      with:
        default_author: github_actions
        branch: master
        message: 'cron: update bips submodule and build'
        push: true
