base_url = "https://bips.dev"

compile_sass = true
ignored_content = [ "*-wordlists.md" ]
taxonomies = [
    { name = "authors" },
    { name = "status" }
]

[markdown]
external_links_target_blank = true
highlight_code = true
highlight_theme = "ayu-light"

[link_checker]
internal_level = "warn"

[slugify]
anchors = "off"
